Nabi 112  yejin  feat s3 upload
team-nabi/nabi-market-server pull request #14
Opened 2023-11-04 12:24 UTC by born-A

## PR 확인 항목 
PR 보내기전에 아래 항목들을 만족 하였는지 체크 해주세요 

- [x] 모진혁 팀에서 정한 커밋 메시지 규칙과 일치하는가?
- [x] 모진혁 팀에서 정한 코딩 컨벤션과 일치하는가?

## PR 종류
어떤 종류의 PR인지 아래 항목중에 체크 해주세요

- [ ] 버그 수정
- [x] 기능 추가
- [ ] 코드 스타일 변경 (formatting, local variables)
- [ ] 리팩토링 (기능 변경 X)
- [ ] 빌드 관련 수정
- [ ] 문서 내용 수정
- [ ] 테스트 추가
- [ ] 그 외, 어떤 종류인지 기입 바람:

## 어떤 기능이 추가 되었나요?

Issue Number: 112

## 기존에 있던 기능에 영향을 주나요?

- [x] 네
- [ ] 아니요

카드 이미지를 requestdto 에서 받는 기존의 방식에서
썸네일이미지 단건 업로드, 카드 상세 이미지 다중 업로드 로 분리하여 구현했습니다.

## Tech Spec
https://www.notion.so/prgrms/Tech-Spec-s3-bc45fc3ef5fc4b7e9bb49297fb5f6b7b?pvs=4

2023-11-04 13:42 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +                .build());
p2
이미지 업로드 먼저 수행하면 card에 thumbNail 필드를 update하는 메소드 없이 만들 수 있을 것 같은데, 어떤가요?

2023-11-04 13:45 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/global/aws/controller/S3FileController.java
> +}
p1
테스트용 파일들이 추가된 것 같습니다. 확인해주세요!

2023-11-04 13:47 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    private String dir = "/test1";
p1
테스트용 코드들 수정해주세요!

2023-11-04 13:50 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    }
p2
예외를 상위로 던지고 있는데, 특별한 이유가 없다면 해당 서비스에서 처리해주는 것이 좋을 것 같은데 어떻게 생각하시나요?

2023-11-04 13:51 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
> +                    .antMatchers(HttpMethod.GET, "/api/v1/users/oauth2/authorize/kakao/**", "/upload/**","/api/vi/users/**").permitAll()
p1
테스트를 위한 코드들 정리해주는 것이 좋아보입니다!

2023-11-04 13:51 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
> +//        antMatchers("/v2/api-docs", "/webjars/**", "/swagger/**", "/h2-console/**");
p1
주석도 정리해주세요!

2023-11-04 13:53 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
> +        CardCreateResponseDTO cardCreateResponseDTO = cardService.save(cardCreateRequestDTO,thumbnail,files);
p1
혹시 api 명세가 바뀌는 부분이라면 프론트분들께도 말씀드리는 것이 좋아보입니다.

2023-11-04 13:54 UTC, hi-june requested changes
코드 리뷰 끝마쳤습니다! 검토해주시면 감사하겠습니다 :)

2023-11-04 14:36 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    }
해당 서비스 내에서 try/catch 하는게 맞는거 같습니다 ! 수정하겠습니다 !

2023-11-04 14:37 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    private String dir = "/test1";
@hi-june  dir의 경우 임의로 넣었는데, 해당 부분은 따로 빼두겠습니다 !

2023-11-04 14:47 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +                .build());
@hi-june CardImageRepository에 저장만 되는 로직이라 update 해주는 메서드가 없으면 null이 되어,
setThumbnail 메서드거 팔요하다고 생각합니다 !
준혁님이 생각하시는 로직 흐름을 구체적으로 알고싶습니다 ...! 👀

2023-11-04 15:05 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +                .build());
@hi-june CardImageRepository에 해당 cardId만을 들고 저장이 되는 것이기에,
따로 set해주지 않으면 null이 들어가 setThumbnailImage 메서드가 필요하다고 생각합니다 !
준혁님이 생각하시는 방향에 대해서 구체적으로 알고싶습니다..! 🤩

2023-11-04 15:08 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/controller/S3FileController.java
> +}
e2ccffee600dc7ddfede435150a81c515a58b38e

2023-11-04 15:08 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    private String dir = "/test1";
0d93a1a8d4ea7a593db1974e16221395515d7c50

2023-11-04 15:10 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    }
12d5782accabaa028374d647f2c3096261428615

2023-11-04 15:10 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
> +                    .antMatchers(HttpMethod.GET, "/api/v1/users/oauth2/authorize/kakao/**", "/upload/**","/api/vi/users/**").permitAll()
d41d1c2bd711f232fe30f51a2a9fab2e9263e197

2023-11-04 15:10 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
> +//        antMatchers("/v2/api-docs", "/webjars/**", "/swagger/**", "/h2-console/**");
d41d1c2bd711f232fe30f51a2a9fab2e9263e197

2023-11-04 16:56 UTC, born-A commented
# 추가 기능 구현
- 카드 유저 도메인 별 폴더 생성 -> 카드 id , user id 별로 이미지 들어가게 수정
- Domain enum 클래스 추가
- 삭제 기능 추가
- 프로필 업로드, 썸네일 업로드의 경우 단건 업로드 이기에 이미 존재할 시에 기존 이미지 삭제 후 업로드 

## 해당 내용 커밋
<img width="1290" alt="image" src="https://github.com/team-nabi/nabi-market-server/assets/93516595/99b77182-ae2e-4eb2-878c-99abba31d3f3">

## 동작 이미지
<img width="1144" alt="image" src="https://github.com/team-nabi/nabi-market-server/assets/93516595/a179a647-d08e-44b6-9313-96265e51c8fe">
<img width="1182" alt="image" src="https://github.com/team-nabi/nabi-market-server/assets/93516595/c6781098-d63a-4fff-9985-34dee5d27471">

2023-11-05 03:11 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
> +//    @NotBlank(message = "공백을 허용하지 않습니다.")
p1
사용하지 않는 코드는 삭제해주세요 !

2023-11-05 03:17 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +            List<MultipartFile> files
p1
명시적으로 무슨 file인지 적어주는 것은 어떨까요 ? (ex : imageFiles)

2023-11-05 03:25 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/cardimage/service/CardImageService.java
> +        }
p1
해당 코드는 기존 card의 thumNailImage가 존재할 경우, 이미지를 삭제하고 있습니다.
그렇다면 새로 받은 MultipartFile을 새로운 썸네일 이미지로 등록해야 할 것 같은데 이 메소드에서는 해당 로직이 보이질 않습니다.
혹시 제가 이해한 바가 맞을까요 ?

2023-11-05 03:44 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
> +    }
p3
set~ 보다는 해당 메소드가 쓰이는 문맥에 어울리는 메소드명으로 바꾸는 것은 어떨까요 ? ex : updateThumbNailImage

2023-11-05 03:45 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/cardimage/service/CardImageService.java
> +            cardImageRepository.save(cardImage);
p1
이부분이 아마 insert쿼리가 uploadFileList갯수만큼 나갈 것 같습니다.
해당 부분은 jdbc bulk insert로 처리가능한것으로 알고 있는데, 추후 반영하실 계획인가요 ?!

2023-11-05 03:55 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
> +    public SingleResult<UserResponseDTO>  uploadFile(
p1
해당 메소드 이름은 저희 팀 컨벤션(CRUD + 도메인명 + 수단)으로 바꿀 수 있을 것 같습니다.

2023-11-05 03:56 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
> +        userService.updateImageUrl(userId, file);
p1
해당 메소드 명도 위의 코멘트와 동일할 것 같습니다.

2023-11-05 03:58 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
> +    @PostMapping("/image-url")
p1
저희 명세서와 url이 맞지 않는 것 같습니다. 확인후 수정 부탁드릴게요.
응답 또한 바뀌는 것이 있다면 프론트분들과 논의 후 수정이 필요할 것 같습니다.(프론트분들이 api 사용하기 전이라면 먼저 바꾼 이후 
통보 드려도 좋구요)

2023-11-05 04:01 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    private String defaultUrl = "https://airplanning-bucket.s3.ap-northeast-2.amazonaws.com";
p1
해당 Url은 상수로 바꾸는 것이 어떨까요 ?

2023-11-05 04:02 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    private String subDir;
p3
해당 필드는 모두 지역변수로만 사용되고 있는 것 같습니다.
service의 필드로 선언하신 이유가 있을까요 ?

2023-11-05 04:03 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +            amazonS3.putObject(bucketDir, fileName, file.getInputStream(), getObjectMetadata(file));
p1
개행 컨벤션 준수 부탁드려요 !

2023-11-05 04:03 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    public String uploadFile(String domain, Long id, MultipartFile file) {
p1
개행 컨벤션 준수 부탁드려요 !

2023-11-05 04:03 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    public List<String> uploadFileList(String domain, Long id, List<MultipartFile> multipartFiles) {
p1
개행 컨벤션 준수 부탁드려요 !
+ 두번째 파라미터(id)는 무슨 id인가요 ? 명시적으로 나타내는 것이 좋을 것 같습니다

2023-11-05 04:05 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/global/config/AWSConfig.java
> +    private String region = "ap-northeast-2"; // Bucket Region (서울)
p1
해당 필드는 상수로 바꾸는 것이 어떨까요?

2023-11-05 06:41 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
> +    private final S3FileUploadService s3FileUploadService;
p1
해당 fileuploadService는 컨트롤러 내에서 사용되지 않는 것 같은데, 맞을까요 ?!

2023-11-05 06:46 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/global/aws/controller/S3FileController.java
> +public class S3FileController {
p3
제 생각에는 upload하는 api가 따로 필요 없이, fileservice만 구현하여 UserService, cardImageService등에서만 fileuploadService만 의존하면 된다고 생각했습니다.
따로 controller를 만들어 주어 api를 만드신 이유가 있을까요 ?

2023-11-05 12:15 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
> +//    @NotBlank(message = "공백을 허용하지 않습니다.")
@BeommoKoo-dev 해당 코드가 validation 부분이라, 준혁님이 검토를 해보신다고 하셔서 우선 살려두었습니다 !

2023-11-05 12:19 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/cardimage/service/CardImageService.java
> +        }
@BeommoKoo-dev 카드에 새로 썸네일 이미지를 업데이트 시켜줘야 하네요 ! 추가하겠습니다 !

2023-11-05 12:57 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    private String subDir;
@BeommoKoo-dev 지역 변수로만 쓰여서 서비스 필드로 사용할 필요가 없는거 같습니다 ! 수정하겠습니다 !

2023-11-05 13:18 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/cardimage/service/CardImageService.java
> +            cardImageRepository.save(cardImage);
@BeommoKoo-dev Bulk insert 관련해서 더 공부해보고 적용하겠습니다 ! 좋은 자료 감사합니다 ! 😄

2023-11-05 13:28 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
> +//    @NotBlank(message = "공백을 허용하지 않습니다.")
040081d80509ffd39e568261a44abf2308584c51 : 주석 제거해두었습니다 !

2023-11-05 13:28 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +            List<MultipartFile> files
c3cc3ea215e353b3b9cd8aeb6f393d7131fb4f2b

2023-11-05 13:29 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/cardimage/service/CardImageService.java
> +        }
39c600213eef4c1a97ed98ec9f2ddb300e7f52c2

2023-11-05 13:29 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
> +    }
12bdf3be55386c5a2418fe94fe5f2b00782fc476

2023-11-05 13:29 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
> +    public SingleResult<UserResponseDTO>  uploadFile(
3c3c8431204760561d11e437f7658fe2e6bd74f3

2023-11-05 13:29 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
> +        userService.updateImageUrl(userId, file);
4225079b4a768df3809b8c381049bc5621db8338

2023-11-05 13:29 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
> +    @PostMapping("/image-url")
d8cc6c0bebcd985324cac22ddb3e16e6fc7d0c0a

2023-11-05 13:30 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    private String defaultUrl = "https://airplanning-bucket.s3.ap-northeast-2.amazonaws.com";
d1bf3d0059a5c8cb247271be3e3e27d28be572d1

2023-11-05 13:30 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    private String subDir;
70a3aaef14d0e062bae92bd29ddfab25c93d8b47

2023-11-05 13:30 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +            amazonS3.putObject(bucketDir, fileName, file.getInputStream(), getObjectMetadata(file));
9782ff73abb0f9e1323a4ae49837e1b1ee1ff2f0

2023-11-05 13:30 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    public String uploadFile(String domain, Long id, MultipartFile file) {
9782ff73abb0f9e1323a4ae49837e1b1ee1ff2f0

2023-11-05 13:30 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
> +    public List<String> uploadFileList(String domain, Long id, List<MultipartFile> multipartFiles) {
2cead2e5463e2747ebb823ebda0f9313a0a0b192

2023-11-05 13:30 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/global/config/AWSConfig.java
> +    private String region = "ap-northeast-2"; // Bucket Region (서울)
d1bf3d0059a5c8cb247271be3e3e27d28be572d1

2023-11-05 13:32 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
> +    private final S3FileUploadService s3FileUploadService;
d1bf3d0059a5c8cb247271be3e3e27d28be572d1

2023-11-05 13:59 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +                .build());
그럼 그 부분은 추후에 같이 논의해보고 수정해도 될 것 같아요!

2023-11-05 14:02 UTC, hi-june approved these changes

2023-11-05 14:25 UTC, merged