NABI-204 기존 api 예외케이스에 따른 코드 수정
team-nabi/nabi-market-server pull request #34
Opened 2023-11-14 08:22 UTC by BeommoKoo-dev

## PR 확인 항목 
PR 보내기전에 아래 항목들을 만족 하였는지 체크 해주세요 

- [x] 모진혁 팀에서 정한 커밋 메시지 규칙과 일치하는가?
- [x] 모진혁 팀에서 정한 코딩 컨벤션과 일치하는가?

## PR 종류
어떤 종류의 PR인지 아래 항목중에 체크 해주세요

- [x] 버그 수정
- [ ] 기능 추가
- [ ] 코드 스타일 변경 (formatting, local variables)
- [x] 리팩토링 (기능 변경 X)
- [ ] 빌드 관련 수정
- [ ] 문서 내용 수정
- [ ] 테스트 추가
- [ ] 그 외, 어떤 종류인지 기입 바람:

## 어떤 기능이 추가 되었나요?

Issue Number: N/A

## 기존에 있던 기능에 영향을 주나요?

- [ ] 네
- [ ] 아니요

## 기타

2023-11-14 13:09 UTC, born-A approved these changes
api 예외케이스들을 확인해서 코드 리팩토링 하시느라 수고하셨습니다 ! 👍 
궁금한점 하나 남겼는데 확인 부탁드려요 !

2023-11-14 13:09 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardDetail.java
> +            .isMyDib(true) //TODO
p1
isMyDib의 경우 아직 개발이 안된걸까요 ?

2023-11-14 13:20 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +   }
p1
기존 코드 주석처리를 그냥 푸신 것 같은데, 해당 기능이 api 명세 수정에 따른 재개발이 필요해서 주석 처리한 것으로 알고 있습니다.

2023-11-14 13:24 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/suggestion/entity/Suggestion.java
> +
p1
외부에서 상태를 받아 update하는 식으로 구성한다면, acceptSuggestion이랑 refuseSuggestion 메소드는 private으로 수정하는 것이 좋아보입니다.

2023-11-14 13:28 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
> +
p1.
enum에서 poke 가능 여부를 판단하는 것 같은데, 위에서 조회한 fromCard와 toCard entity로 pokeAvailable을 충분히 조회할 수 있지 않을까요?

2023-11-14 13:31 UTC, hi-june commented on src/main/resources/application.yml
> +
p1
설정 파일을 분리 하는 것이 좋을 것 같습니다~!

2023-11-14 13:35 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
> +
정확히는 poke가능 여부는 service code에서, poke가 가능하다면 실제로 '두 카드의 가격대가 다른지' 에 대해서 Enum 내부적으로 판단을 합니다. 따라서 다음과 같이 책임을 나누었습니다.
service : 클라측에서 받은 요청을 검사하고, 만약 POKE라면, Enum에게 fromCard와 toCard의 관계가 찔러보기가 될 수 있는지 판단하도록 item객체를 넘겨줌.
enum : 전달받은 fromCard의 item의 가격대, toCard의 item의 가격대를 비교하여 맞지 않으면 실제로 찔러보기가 될 수 있으므로 true를 반환.
이런 로직으로 구성한 이유는, 추후 제안 타입의 조건이 변경될 시, Enum에서 한번에서 관리하는것이 유지보수 측면에서 좋기 때문입니다. (ex : fromCard의 가격대가 toCard의 가격대보다 한단계 낮아도, 오퍼로 거래 제안을 할 수 있도록 정책이 변경될 시, enum의 isSuggestionAvailble만 변경하면 됨.)
(다만 로직 구현 시 생각이 짧아 fromCard와 toCard의 가격대가 '맞지 않은것'에 대해서만 판단을 하는데, 정확히는 toCard의 가격대가 fromCard의 가격대보다 높아야 true를 반환하는것이 맞아 수정 후 다시 커밋하겠습니다.)

2023-11-14 13:36 UTC, BeommoKoo-dev commented on src/main/resources/application.yml
> +
여느 환경에서도 어플리케이션을 실행할 시 data.sql을 실행하도록 일부러 root yml에 넣어두었습니다. 환경별로 다르게 하는것이 나을까요 ? 고민이네요

2023-11-14 13:39 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +   }
다음 커밋에 개발하려고 주석해제했습니다 ! (실제 개발까지 완료하였습니다 :) )

2023-11-14 13:40 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +
p3
dto에 images가 비어있으면, cardImage 리스트도 빈 리스트가 만들어지게 되니, optional을 안 붙어줘도 괜찮지 않나요?(궁금)

p1
(thumbnail을 cardImage에도 추가하는 부분) update 부분도 동일한 방식으로 수정이 필요할 것 같습니다.

2023-11-14 13:40 UTC, hi-june requested changes
고생하셨습니다!
몇몇 부분 리뷰 남겼습니다

2023-11-14 13:43 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +
Optional의 ofNullable을 이용하여, image가 null이라면(비어있으면) orElse문의 코드를 실행하기 위해 Optional을 붙여주었습니다!
(Optional을 쓰지 않는다면 if문 분기처리로 images null check를 해주어야 합니다.)

2023-11-14 13:43 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +
update부분은 제가 신경쓰지 못했네요 ! 수정하겠습니다.

2023-11-14 13:49 UTC, hi-june commented on src/main/resources/application.yml
> +
사실 이 프로젝트의 경우 상관없긴 하지만 
만약 운영 환경과 개발 환경의 db vendor가 다를 경우 각 환경에 맞는 sql 문도 다르지 않을까.. 하는 생각입니다ㅎㅎ

그냥 제안 정도로만 확인해주셔도 될 것 같습니다.

2023-11-14 13:51 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +
> Optional의 ofNullable을 이용하여, image가 null이라면(비어있으면) orElse문의 코드를 실행하기 위해 Optional을 붙여주었습니다! (Optional을 쓰지 않는다면 if문 분기처리로 images null check를 해주어야 합니다.)

아, 제가 비어있는 상태랑 null 이랑 착각했네요. 확인했습니다!

2023-11-14 13:53 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
> +
> 정확히는 poke가능 여부는 service code에서, poke가 가능하다면 실제로 '두 카드의 가격대가 다른지' 에 대해서 Enum 내부적으로 판단을 합니다. 따라서 다음과 같이 책임을 나누었습니다. service : 클라측에서 받은 요청을 검사하고, 만약 POKE라면, Enum에게 fromCard와 toCard의 관계가 찔러보기가 될 수 있는지 판단하도록 item객체를 넘겨줌. enum : 전달받은 fromCard의 item의 가격대, toCard의 item의 가격대를 비교하여 맞지 않으면 실제로 찔러보기가 될 수 있으므로 true를 반환. 이런 로직으로 구성한 이유는, 추후 제안 타입의 조건이 변경될 시, Enum에서 한번에서 관리하는것이 유지보수 측면에서 좋기 때문입니다. (ex : fromCard의 가격대가 toCard의 가격대보다 한단계 낮아도, 오퍼로 거래 제안을 할 수 있도록 정책이 변경될 시, enum의 isSuggestionAvailble만 변경하면 됨.) (다만 로직 구현 시 생각이 짧아 fromCard와 toCard의 가격대가 '맞지 않은것'에 대해서만 판단을 하는데, 정확히는 toCard의 가격대가 fromCard의 가격대보다 높아야 true를 반환하는것이 맞아 수정 후 다시 커밋하겠습니다.)

넵! 확인했습니다. 감사합니다!!

2023-11-15 02:54 UTC, hi-june approved these changes

2023-11-15 03:38 UTC, merged