NABI-250--feat : 인기상품 조회 기능 추가
team-nabi/nabi-market-server pull request #48
Opened 2023-11-18 06:33 UTC by BeommoKoo-dev

Tech Spec : https://www.notion.so/prgrms/Tech-Spec-3e20145f442b417aa4f495e1eaeefd51?pvs=4

## PR 확인 항목 
PR 보내기전에 아래 항목들을 만족 하였는지 체크 해주세요 

- [x] 모진혁 팀에서 정한 커밋 메시지 규칙과 일치하는가?
- [x] 모진혁 팀에서 정한 코딩 컨벤션과 일치하는가?

## PR 종류
어떤 종류의 PR인지 아래 항목중에 체크 해주세요

- [ ] 버그 수정
- [x] 기능 추가
- [ ] 코드 스타일 변경 (formatting, local variables)
- [ ] 리팩토링 (기능 변경 X)
- [ ] 빌드 관련 수정
- [ ] 문서 내용 수정
- [ ] 테스트 추가
- [ ] 그 외, 어떤 종류인지 기입 바람:

## 어떤 기능이 추가 되었나요?

Issue Number: NABI-250

## 기존에 있던 기능에 영향을 주나요?

- [ ] 네
- [x] 아니요

## 기타

2023-11-18 06:46 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +        if (userRepository.existsById(userId)) {
p1
이 부분 혹시 user가 있으면 예외를 발생시키는 부분인가요?

2023-11-18 06:48 UTC, hi-june commented on src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryImpl.java
> +            .limit(FAMOUS_CARD_SIZE)
p3.
의도하신 바가 조회수 기준으로 내림 차순 정렬하고, 조회수가 같을 시 찜 횟수 기준으로 내림 차순 정렬하신게 맞나요?
저희끼리 사전에 얘기한 정책이 있었는지 궁금합니다(개인적으로는 찬성)!

2023-11-18 06:51 UTC, hi-june commented on src/main/resources/application.yml
> -    defer-datasource-initialization: true
p1
주석을 따로 남겨두신 이유가 없다면 주석도 같이 제거해주는 편이 좋을 것 같습니다~
그리고 sql.init 설정을 아예 제거하면 category insert는 더 이상 안 되는 것이 맞나요?

2023-11-18 06:52 UTC, hi-june requested changes
고생하셨습니다, 리뷰 마쳤습니다! 
몇몇 부분 한 번 체크해주시면 감사하겠습니다!

2023-11-18 07:04 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +        if (userRepository.existsById(userId)) {
제 일방적인 실수입니다 ! 해당 코드는 왜 !가 지워졌는지 모르겠네요 .. 수정하겠습니다 !

2023-11-18 07:04 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +        if (userRepository.existsById(userId)) {
꼼꼼한 리뷰 감사드려요 ㅜㅜ 큰일날뻔 했습니다

2023-11-18 07:05 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryImpl.java
> +            .limit(FAMOUS_CARD_SIZE)
넵 맞습니다 ! 따로 사전에 얘기한 부분은 없지만, 약식으로 조회수 합산 기준으로만 내려드린다고 남겨놓았습니다. (찜 갯수 기준 정렬은 조회수가 같을시에 대비해 추가해 두었습니다.)

2023-11-18 07:07 UTC, BeommoKoo-dev commented on src/main/resources/application.yml
> -    defer-datasource-initialization: true
반영하겠습니다 !
질문에 답변드리자면, application-prod에 별도로 작성해 두었습니다. 다만 로컬에선 중복 insert가 작동하지 않지만, 서버에서는 기존에 데이터가 존재하더라도 insert되는 이슈가 있어 추후 해결 예정입니다. (지금은 서버뜰때마다 수동으로 중복 데이터를 삭제중입니다..)

2023-11-20 05:59 UTC, born-A approved these changes
인기상품 조회 기능까지 추가하시느라 수고하셨습니다 ! 👍

2023-11-20 05:59 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryImpl.java
> +    private static final int FAMOUS_CARD_SIZE = 5;
p1
노출할 size는 pathvariable로 받는게 어떨까요 ?
card 목록 조회도 정책상으론 10개 받기로 정해져 있지만, size를 pathvariable로 받기 때문에 통일하면 좋을거 같습니다 !

2023-11-20 05:59 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +        CardListResponseDTO<CardFamousResponseDTO> response = new CardListResponseDTO<>(cardList);
p2
변수명을 cardFamousListResponse로 바꾸면 어떨까요 ?

2023-11-20 06:05 UTC, BeommoKoo-dev commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +        CardListResponseDTO<CardFamousResponseDTO> response = new CardListResponseDTO<>(cardList);
dto의 필드 이름이 cardList라, 일부러 통일시켰습니다! 어떻게 생각하시나용

2023-11-20 06:47 UTC, born-A approved these changes

2023-11-20 06:47 UTC, born-A commented on src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
> +        CardListResponseDTO<CardFamousResponseDTO> response = new CardListResponseDTO<>(cardList);
아하 그렇군요 ! response 라는 변수명이 모호하게 느껴져서 명확한 네이밍이 들어갔으면 좋지 않을까 싶습니다 !

2023-11-20 06:47 UTC, hi-june approved these changes

2023-11-20 06:48 UTC, merged